const getters = {
  sidebar: (state) => state.app.sidebar,
  device: (state) => state.app.device,
  filesize: (state) => state.app.filesize,
  timeInterval: (state) => state.app.timeInterval,
  token: (state) => state.user.token,
  kind: (state) => state.user.kind,
  project_key: (state) => state.user.project_key,
  avatar: (state) => state.user.avatar,
  userInfo: (state) => state.user.userInfo,
  name: (state) => state.user.name,
  tipMessageStatus: (state) => state.user.tipMessageStatus,
  searchList: (state) => state.app.searchList,
  hxcloudData: (state) => state.app.hxcloudData,
  bottomContral: (state) => state.app.bottomContral,
  ttyStatus: (state) => state.app.ttyStatus,
  addRouters: (state) => state.permission.addRouters,
  routers: (state) => state.permission.routers,
  path: (state) => state.permission.path,
  hidden: (state) => state.permission.hidden,
  transmissionUserInfo: (state) => state.transfer.transmissionUserInfo,
  transmissionInfo: (state) => state.transfer.transmissionInfo,
  transferDialogStatus: (state) => state.transfer.transferDialogStatus,
  windowstatus: (state) => state.transfer.windowstatus,
  macstatus: (state) => state.transfer.macstatus,
};
export default getters;
