// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ee_fwd_def.proto

package com.lnjoying.justice.schema.msg;

public final class EeFwdDef {
  private EeFwdDef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface msg_fwd_data_req_bodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:justice.net.msg_fwd_data_req_body)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string data_id = 1;</code>
     */
    java.lang.String getDataId();
    /**
     * <code>string data_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getDataIdBytes();

    /**
     * <code>bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>string proto = 3;</code>
     */
    java.lang.String getProto();
    /**
     * <code>string proto = 3;</code>
     */
    com.google.protobuf.ByteString
        getProtoBytes();

    /**
     * <pre>
     *if proto is tcp or udp, the address is "ip:port"; if proto is unix/npipe, the address is the path.
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    java.lang.String getAddress();
    /**
     * <pre>
     *if proto is tcp or udp, the address is "ip:port"; if proto is unix/npipe, the address is the path.
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code justice.net.msg_fwd_data_req_body}
   */
  public  static final class msg_fwd_data_req_body extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:justice.net.msg_fwd_data_req_body)
      msg_fwd_data_req_bodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use msg_fwd_data_req_body.newBuilder() to construct.
    private msg_fwd_data_req_body(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private msg_fwd_data_req_body() {
      dataId_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      proto_ = "";
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new msg_fwd_data_req_body();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private msg_fwd_data_req_body(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              dataId_ = s;
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              proto_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_data_req_body_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_data_req_body_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.class, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.Builder.class);
    }

    public static final int DATA_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object dataId_;
    /**
     * <code>string data_id = 1;</code>
     */
    public java.lang.String getDataId() {
      java.lang.Object ref = dataId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataId_ = s;
        return s;
      }
    }
    /**
     * <code>string data_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataIdBytes() {
      java.lang.Object ref = dataId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int PROTO_FIELD_NUMBER = 3;
    private volatile java.lang.Object proto_;
    /**
     * <code>string proto = 3;</code>
     */
    public java.lang.String getProto() {
      java.lang.Object ref = proto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proto_ = s;
        return s;
      }
    }
    /**
     * <code>string proto = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProtoBytes() {
      java.lang.Object ref = proto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private volatile java.lang.Object address_;
    /**
     * <pre>
     *if proto is tcp or udp, the address is "ip:port"; if proto is unix/npipe, the address is the path.
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *if proto is tcp or udp, the address is "ip:port"; if proto is unix/npipe, the address is the path.
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDataIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      if (!getProtoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, proto_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, address_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDataIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (!getProtoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, proto_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body)) {
        return super.equals(obj);
      }
      com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body other = (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) obj;

      if (!getDataId()
          .equals(other.getDataId())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getProto()
          .equals(other.getProto())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDataId().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + PROTO_FIELD_NUMBER;
      hash = (53 * hash) + getProto().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code justice.net.msg_fwd_data_req_body}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:justice.net.msg_fwd_data_req_body)
        com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_bodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_data_req_body_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_data_req_body_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.class, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.Builder.class);
      }

      // Construct using com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataId_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        proto_ = "";

        address_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_data_req_body_descriptor;
      }

      @java.lang.Override
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body getDefaultInstanceForType() {
        return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.getDefaultInstance();
      }

      @java.lang.Override
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body build() {
        com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body buildPartial() {
        com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body result = new com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body(this);
        result.dataId_ = dataId_;
        result.data_ = data_;
        result.proto_ = proto_;
        result.address_ = address_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) {
          return mergeFrom((com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body other) {
        if (other == com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.getDefaultInstance()) return this;
        if (!other.getDataId().isEmpty()) {
          dataId_ = other.dataId_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (!other.getProto().isEmpty()) {
          proto_ = other.proto_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object dataId_ = "";
      /**
       * <code>string data_id = 1;</code>
       */
      public java.lang.String getDataId() {
        java.lang.Object ref = dataId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataIdBytes() {
        java.lang.Object ref = dataId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data_id = 1;</code>
       */
      public Builder setDataId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data_id = 1;</code>
       */
      public Builder clearDataId() {
        
        dataId_ = getDefaultInstance().getDataId();
        onChanged();
        return this;
      }
      /**
       * <code>string data_id = 1;</code>
       */
      public Builder setDataIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private java.lang.Object proto_ = "";
      /**
       * <code>string proto = 3;</code>
       */
      public java.lang.String getProto() {
        java.lang.Object ref = proto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          proto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string proto = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProtoBytes() {
        java.lang.Object ref = proto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          proto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string proto = 3;</code>
       */
      public Builder setProto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        proto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string proto = 3;</code>
       */
      public Builder clearProto() {
        
        proto_ = getDefaultInstance().getProto();
        onChanged();
        return this;
      }
      /**
       * <code>string proto = 3;</code>
       */
      public Builder setProtoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        proto_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <pre>
       *if proto is tcp or udp, the address is "ip:port"; if proto is unix/npipe, the address is the path.
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *if proto is tcp or udp, the address is "ip:port"; if proto is unix/npipe, the address is the path.
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *if proto is tcp or udp, the address is "ip:port"; if proto is unix/npipe, the address is the path.
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *if proto is tcp or udp, the address is "ip:port"; if proto is unix/npipe, the address is the path.
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *if proto is tcp or udp, the address is "ip:port"; if proto is unix/npipe, the address is the path.
       * </pre>
       *
       * <code>string address = 4;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:justice.net.msg_fwd_data_req_body)
    }

    // @@protoc_insertion_point(class_scope:justice.net.msg_fwd_data_req_body)
    private static final com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body();
    }

    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<msg_fwd_data_req_body>
        PARSER = new com.google.protobuf.AbstractParser<msg_fwd_data_req_body>() {
      @java.lang.Override
      public msg_fwd_data_req_body parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new msg_fwd_data_req_body(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<msg_fwd_data_req_body> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<msg_fwd_data_req_body> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface msg_fwd_data_rsp_bodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:justice.net.msg_fwd_data_rsp_body)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string data_id = 1;</code>
     */
    java.lang.String getDataId();
    /**
     * <code>string data_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getDataIdBytes();

    /**
     * <code>bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>int32 error_code = 3;</code>
     */
    int getErrorCode();
  }
  /**
   * Protobuf type {@code justice.net.msg_fwd_data_rsp_body}
   */
  public  static final class msg_fwd_data_rsp_body extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:justice.net.msg_fwd_data_rsp_body)
      msg_fwd_data_rsp_bodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use msg_fwd_data_rsp_body.newBuilder() to construct.
    private msg_fwd_data_rsp_body(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private msg_fwd_data_rsp_body() {
      dataId_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new msg_fwd_data_rsp_body();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private msg_fwd_data_rsp_body(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              dataId_ = s;
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            case 24: {

              errorCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_data_rsp_body_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_data_rsp_body_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.class, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.Builder.class);
    }

    public static final int DATA_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object dataId_;
    /**
     * <code>string data_id = 1;</code>
     */
    public java.lang.String getDataId() {
      java.lang.Object ref = dataId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataId_ = s;
        return s;
      }
    }
    /**
     * <code>string data_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataIdBytes() {
      java.lang.Object ref = dataId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int ERROR_CODE_FIELD_NUMBER = 3;
    private int errorCode_;
    /**
     * <code>int32 error_code = 3;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDataIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      if (errorCode_ != 0) {
        output.writeInt32(3, errorCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDataIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errorCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body)) {
        return super.equals(obj);
      }
      com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body other = (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) obj;

      if (!getDataId()
          .equals(other.getDataId())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getErrorCode()
          != other.getErrorCode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDataId().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code justice.net.msg_fwd_data_rsp_body}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:justice.net.msg_fwd_data_rsp_body)
        com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_bodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_data_rsp_body_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_data_rsp_body_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.class, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.Builder.class);
      }

      // Construct using com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataId_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        errorCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_data_rsp_body_descriptor;
      }

      @java.lang.Override
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body getDefaultInstanceForType() {
        return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.getDefaultInstance();
      }

      @java.lang.Override
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body build() {
        com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body buildPartial() {
        com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body result = new com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body(this);
        result.dataId_ = dataId_;
        result.data_ = data_;
        result.errorCode_ = errorCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) {
          return mergeFrom((com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body other) {
        if (other == com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.getDefaultInstance()) return this;
        if (!other.getDataId().isEmpty()) {
          dataId_ = other.dataId_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object dataId_ = "";
      /**
       * <code>string data_id = 1;</code>
       */
      public java.lang.String getDataId() {
        java.lang.Object ref = dataId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataIdBytes() {
        java.lang.Object ref = dataId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data_id = 1;</code>
       */
      public Builder setDataId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data_id = 1;</code>
       */
      public Builder clearDataId() {
        
        dataId_ = getDefaultInstance().getDataId();
        onChanged();
        return this;
      }
      /**
       * <code>string data_id = 1;</code>
       */
      public Builder setDataIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>int32 error_code = 3;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 error_code = 3;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 error_code = 3;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:justice.net.msg_fwd_data_rsp_body)
    }

    // @@protoc_insertion_point(class_scope:justice.net.msg_fwd_data_rsp_body)
    private static final com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body();
    }

    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<msg_fwd_data_rsp_body>
        PARSER = new com.google.protobuf.AbstractParser<msg_fwd_data_rsp_body>() {
      @java.lang.Override
      public msg_fwd_data_rsp_body parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new msg_fwd_data_rsp_body(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<msg_fwd_data_rsp_body> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<msg_fwd_data_rsp_body> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface msg_fwd_operator_bodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:justice.net.msg_fwd_operator_body)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string operator_type = 1;</code>
     */
    java.lang.String getOperatorType();
    /**
     * <code>string operator_type = 1;</code>
     */
    com.google.protobuf.ByteString
        getOperatorTypeBytes();

    /**
     * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
     */
    boolean hasFwdDataReqBody();
    /**
     * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
     */
    com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body getFwdDataReqBody();
    /**
     * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
     */
    com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_bodyOrBuilder getFwdDataReqBodyOrBuilder();

    /**
     * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
     */
    boolean hasFwdDataRspBody();
    /**
     * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
     */
    com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body getFwdDataRspBody();
    /**
     * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
     */
    com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_bodyOrBuilder getFwdDataRspBodyOrBuilder();

    public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body.FuncBodyCase getFuncBodyCase();
  }
  /**
   * Protobuf type {@code justice.net.msg_fwd_operator_body}
   */
  public  static final class msg_fwd_operator_body extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:justice.net.msg_fwd_operator_body)
      msg_fwd_operator_bodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use msg_fwd_operator_body.newBuilder() to construct.
    private msg_fwd_operator_body(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private msg_fwd_operator_body() {
      operatorType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new msg_fwd_operator_body();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private msg_fwd_operator_body(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              operatorType_ = s;
              break;
            }
            case 290: {
              com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.Builder subBuilder = null;
              if (funcBodyCase_ == 36) {
                subBuilder = ((com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) funcBody_).toBuilder();
              }
              funcBody_ =
                  input.readMessage(com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) funcBody_);
                funcBody_ = subBuilder.buildPartial();
              }
              funcBodyCase_ = 36;
              break;
            }
            case 298: {
              com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.Builder subBuilder = null;
              if (funcBodyCase_ == 37) {
                subBuilder = ((com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) funcBody_).toBuilder();
              }
              funcBody_ =
                  input.readMessage(com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) funcBody_);
                funcBody_ = subBuilder.buildPartial();
              }
              funcBodyCase_ = 37;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_operator_body_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_operator_body_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body.class, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body.Builder.class);
    }

    private int funcBodyCase_ = 0;
    private java.lang.Object funcBody_;
    public enum FuncBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      FWD_DATA_REQ_BODY(36),
      FWD_DATA_RSP_BODY(37),
      FUNCBODY_NOT_SET(0);
      private final int value;
      private FuncBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static FuncBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static FuncBodyCase forNumber(int value) {
        switch (value) {
          case 36: return FWD_DATA_REQ_BODY;
          case 37: return FWD_DATA_RSP_BODY;
          case 0: return FUNCBODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public FuncBodyCase
    getFuncBodyCase() {
      return FuncBodyCase.forNumber(
          funcBodyCase_);
    }

    public static final int OPERATOR_TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object operatorType_;
    /**
     * <code>string operator_type = 1;</code>
     */
    public java.lang.String getOperatorType() {
      java.lang.Object ref = operatorType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operatorType_ = s;
        return s;
      }
    }
    /**
     * <code>string operator_type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOperatorTypeBytes() {
      java.lang.Object ref = operatorType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operatorType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FWD_DATA_REQ_BODY_FIELD_NUMBER = 36;
    /**
     * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
     */
    public boolean hasFwdDataReqBody() {
      return funcBodyCase_ == 36;
    }
    /**
     * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
     */
    public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body getFwdDataReqBody() {
      if (funcBodyCase_ == 36) {
         return (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) funcBody_;
      }
      return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.getDefaultInstance();
    }
    /**
     * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
     */
    public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_bodyOrBuilder getFwdDataReqBodyOrBuilder() {
      if (funcBodyCase_ == 36) {
         return (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) funcBody_;
      }
      return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.getDefaultInstance();
    }

    public static final int FWD_DATA_RSP_BODY_FIELD_NUMBER = 37;
    /**
     * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
     */
    public boolean hasFwdDataRspBody() {
      return funcBodyCase_ == 37;
    }
    /**
     * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
     */
    public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body getFwdDataRspBody() {
      if (funcBodyCase_ == 37) {
         return (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) funcBody_;
      }
      return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.getDefaultInstance();
    }
    /**
     * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
     */
    public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_bodyOrBuilder getFwdDataRspBodyOrBuilder() {
      if (funcBodyCase_ == 37) {
         return (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) funcBody_;
      }
      return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOperatorTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operatorType_);
      }
      if (funcBodyCase_ == 36) {
        output.writeMessage(36, (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) funcBody_);
      }
      if (funcBodyCase_ == 37) {
        output.writeMessage(37, (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) funcBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOperatorTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operatorType_);
      }
      if (funcBodyCase_ == 36) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(36, (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) funcBody_);
      }
      if (funcBodyCase_ == 37) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(37, (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) funcBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body)) {
        return super.equals(obj);
      }
      com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body other = (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body) obj;

      if (!getOperatorType()
          .equals(other.getOperatorType())) return false;
      if (!getFuncBodyCase().equals(other.getFuncBodyCase())) return false;
      switch (funcBodyCase_) {
        case 36:
          if (!getFwdDataReqBody()
              .equals(other.getFwdDataReqBody())) return false;
          break;
        case 37:
          if (!getFwdDataRspBody()
              .equals(other.getFwdDataRspBody())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATOR_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getOperatorType().hashCode();
      switch (funcBodyCase_) {
        case 36:
          hash = (37 * hash) + FWD_DATA_REQ_BODY_FIELD_NUMBER;
          hash = (53 * hash) + getFwdDataReqBody().hashCode();
          break;
        case 37:
          hash = (37 * hash) + FWD_DATA_RSP_BODY_FIELD_NUMBER;
          hash = (53 * hash) + getFwdDataRspBody().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code justice.net.msg_fwd_operator_body}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:justice.net.msg_fwd_operator_body)
        com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_bodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_operator_body_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_operator_body_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body.class, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body.Builder.class);
      }

      // Construct using com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        operatorType_ = "";

        funcBodyCase_ = 0;
        funcBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lnjoying.justice.schema.msg.EeFwdDef.internal_static_justice_net_msg_fwd_operator_body_descriptor;
      }

      @java.lang.Override
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body getDefaultInstanceForType() {
        return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body.getDefaultInstance();
      }

      @java.lang.Override
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body build() {
        com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body buildPartial() {
        com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body result = new com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body(this);
        result.operatorType_ = operatorType_;
        if (funcBodyCase_ == 36) {
          if (fwdDataReqBodyBuilder_ == null) {
            result.funcBody_ = funcBody_;
          } else {
            result.funcBody_ = fwdDataReqBodyBuilder_.build();
          }
        }
        if (funcBodyCase_ == 37) {
          if (fwdDataRspBodyBuilder_ == null) {
            result.funcBody_ = funcBody_;
          } else {
            result.funcBody_ = fwdDataRspBodyBuilder_.build();
          }
        }
        result.funcBodyCase_ = funcBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body) {
          return mergeFrom((com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body other) {
        if (other == com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body.getDefaultInstance()) return this;
        if (!other.getOperatorType().isEmpty()) {
          operatorType_ = other.operatorType_;
          onChanged();
        }
        switch (other.getFuncBodyCase()) {
          case FWD_DATA_REQ_BODY: {
            mergeFwdDataReqBody(other.getFwdDataReqBody());
            break;
          }
          case FWD_DATA_RSP_BODY: {
            mergeFwdDataRspBody(other.getFwdDataRspBody());
            break;
          }
          case FUNCBODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int funcBodyCase_ = 0;
      private java.lang.Object funcBody_;
      public FuncBodyCase
          getFuncBodyCase() {
        return FuncBodyCase.forNumber(
            funcBodyCase_);
      }

      public Builder clearFuncBody() {
        funcBodyCase_ = 0;
        funcBody_ = null;
        onChanged();
        return this;
      }


      private java.lang.Object operatorType_ = "";
      /**
       * <code>string operator_type = 1;</code>
       */
      public java.lang.String getOperatorType() {
        java.lang.Object ref = operatorType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operatorType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string operator_type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOperatorTypeBytes() {
        java.lang.Object ref = operatorType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operatorType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string operator_type = 1;</code>
       */
      public Builder setOperatorType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        operatorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string operator_type = 1;</code>
       */
      public Builder clearOperatorType() {
        
        operatorType_ = getDefaultInstance().getOperatorType();
        onChanged();
        return this;
      }
      /**
       * <code>string operator_type = 1;</code>
       */
      public Builder setOperatorTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        operatorType_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.Builder, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_bodyOrBuilder> fwdDataReqBodyBuilder_;
      /**
       * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
       */
      public boolean hasFwdDataReqBody() {
        return funcBodyCase_ == 36;
      }
      /**
       * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
       */
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body getFwdDataReqBody() {
        if (fwdDataReqBodyBuilder_ == null) {
          if (funcBodyCase_ == 36) {
            return (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) funcBody_;
          }
          return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.getDefaultInstance();
        } else {
          if (funcBodyCase_ == 36) {
            return fwdDataReqBodyBuilder_.getMessage();
          }
          return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.getDefaultInstance();
        }
      }
      /**
       * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
       */
      public Builder setFwdDataReqBody(com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body value) {
        if (fwdDataReqBodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          funcBody_ = value;
          onChanged();
        } else {
          fwdDataReqBodyBuilder_.setMessage(value);
        }
        funcBodyCase_ = 36;
        return this;
      }
      /**
       * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
       */
      public Builder setFwdDataReqBody(
          com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.Builder builderForValue) {
        if (fwdDataReqBodyBuilder_ == null) {
          funcBody_ = builderForValue.build();
          onChanged();
        } else {
          fwdDataReqBodyBuilder_.setMessage(builderForValue.build());
        }
        funcBodyCase_ = 36;
        return this;
      }
      /**
       * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
       */
      public Builder mergeFwdDataReqBody(com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body value) {
        if (fwdDataReqBodyBuilder_ == null) {
          if (funcBodyCase_ == 36 &&
              funcBody_ != com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.getDefaultInstance()) {
            funcBody_ = com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.newBuilder((com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) funcBody_)
                .mergeFrom(value).buildPartial();
          } else {
            funcBody_ = value;
          }
          onChanged();
        } else {
          if (funcBodyCase_ == 36) {
            fwdDataReqBodyBuilder_.mergeFrom(value);
          }
          fwdDataReqBodyBuilder_.setMessage(value);
        }
        funcBodyCase_ = 36;
        return this;
      }
      /**
       * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
       */
      public Builder clearFwdDataReqBody() {
        if (fwdDataReqBodyBuilder_ == null) {
          if (funcBodyCase_ == 36) {
            funcBodyCase_ = 0;
            funcBody_ = null;
            onChanged();
          }
        } else {
          if (funcBodyCase_ == 36) {
            funcBodyCase_ = 0;
            funcBody_ = null;
          }
          fwdDataReqBodyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
       */
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.Builder getFwdDataReqBodyBuilder() {
        return getFwdDataReqBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
       */
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_bodyOrBuilder getFwdDataReqBodyOrBuilder() {
        if ((funcBodyCase_ == 36) && (fwdDataReqBodyBuilder_ != null)) {
          return fwdDataReqBodyBuilder_.getMessageOrBuilder();
        } else {
          if (funcBodyCase_ == 36) {
            return (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) funcBody_;
          }
          return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.getDefaultInstance();
        }
      }
      /**
       * <code>.justice.net.msg_fwd_data_req_body fwd_data_req_body = 36;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.Builder, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_bodyOrBuilder> 
          getFwdDataReqBodyFieldBuilder() {
        if (fwdDataReqBodyBuilder_ == null) {
          if (!(funcBodyCase_ == 36)) {
            funcBody_ = com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.getDefaultInstance();
          }
          fwdDataReqBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body.Builder, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_bodyOrBuilder>(
                  (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_req_body) funcBody_,
                  getParentForChildren(),
                  isClean());
          funcBody_ = null;
        }
        funcBodyCase_ = 36;
        onChanged();;
        return fwdDataReqBodyBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.Builder, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_bodyOrBuilder> fwdDataRspBodyBuilder_;
      /**
       * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
       */
      public boolean hasFwdDataRspBody() {
        return funcBodyCase_ == 37;
      }
      /**
       * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
       */
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body getFwdDataRspBody() {
        if (fwdDataRspBodyBuilder_ == null) {
          if (funcBodyCase_ == 37) {
            return (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) funcBody_;
          }
          return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.getDefaultInstance();
        } else {
          if (funcBodyCase_ == 37) {
            return fwdDataRspBodyBuilder_.getMessage();
          }
          return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.getDefaultInstance();
        }
      }
      /**
       * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
       */
      public Builder setFwdDataRspBody(com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body value) {
        if (fwdDataRspBodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          funcBody_ = value;
          onChanged();
        } else {
          fwdDataRspBodyBuilder_.setMessage(value);
        }
        funcBodyCase_ = 37;
        return this;
      }
      /**
       * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
       */
      public Builder setFwdDataRspBody(
          com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.Builder builderForValue) {
        if (fwdDataRspBodyBuilder_ == null) {
          funcBody_ = builderForValue.build();
          onChanged();
        } else {
          fwdDataRspBodyBuilder_.setMessage(builderForValue.build());
        }
        funcBodyCase_ = 37;
        return this;
      }
      /**
       * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
       */
      public Builder mergeFwdDataRspBody(com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body value) {
        if (fwdDataRspBodyBuilder_ == null) {
          if (funcBodyCase_ == 37 &&
              funcBody_ != com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.getDefaultInstance()) {
            funcBody_ = com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.newBuilder((com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) funcBody_)
                .mergeFrom(value).buildPartial();
          } else {
            funcBody_ = value;
          }
          onChanged();
        } else {
          if (funcBodyCase_ == 37) {
            fwdDataRspBodyBuilder_.mergeFrom(value);
          }
          fwdDataRspBodyBuilder_.setMessage(value);
        }
        funcBodyCase_ = 37;
        return this;
      }
      /**
       * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
       */
      public Builder clearFwdDataRspBody() {
        if (fwdDataRspBodyBuilder_ == null) {
          if (funcBodyCase_ == 37) {
            funcBodyCase_ = 0;
            funcBody_ = null;
            onChanged();
          }
        } else {
          if (funcBodyCase_ == 37) {
            funcBodyCase_ = 0;
            funcBody_ = null;
          }
          fwdDataRspBodyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
       */
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.Builder getFwdDataRspBodyBuilder() {
        return getFwdDataRspBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
       */
      public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_bodyOrBuilder getFwdDataRspBodyOrBuilder() {
        if ((funcBodyCase_ == 37) && (fwdDataRspBodyBuilder_ != null)) {
          return fwdDataRspBodyBuilder_.getMessageOrBuilder();
        } else {
          if (funcBodyCase_ == 37) {
            return (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) funcBody_;
          }
          return com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.getDefaultInstance();
        }
      }
      /**
       * <code>.justice.net.msg_fwd_data_rsp_body fwd_data_rsp_body = 37;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.Builder, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_bodyOrBuilder> 
          getFwdDataRspBodyFieldBuilder() {
        if (fwdDataRspBodyBuilder_ == null) {
          if (!(funcBodyCase_ == 37)) {
            funcBody_ = com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.getDefaultInstance();
          }
          fwdDataRspBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body.Builder, com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_bodyOrBuilder>(
                  (com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_data_rsp_body) funcBody_,
                  getParentForChildren(),
                  isClean());
          funcBody_ = null;
        }
        funcBodyCase_ = 37;
        onChanged();;
        return fwdDataRspBodyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:justice.net.msg_fwd_operator_body)
    }

    // @@protoc_insertion_point(class_scope:justice.net.msg_fwd_operator_body)
    private static final com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body();
    }

    public static com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<msg_fwd_operator_body>
        PARSER = new com.google.protobuf.AbstractParser<msg_fwd_operator_body>() {
      @java.lang.Override
      public msg_fwd_operator_body parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new msg_fwd_operator_body(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<msg_fwd_operator_body> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<msg_fwd_operator_body> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lnjoying.justice.schema.msg.EeFwdDef.msg_fwd_operator_body getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_justice_net_msg_fwd_data_req_body_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_justice_net_msg_fwd_data_req_body_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_justice_net_msg_fwd_data_rsp_body_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_justice_net_msg_fwd_data_rsp_body_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_justice_net_msg_fwd_operator_body_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_justice_net_msg_fwd_operator_body_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ee_fwd_def.proto\022\013justice.net\"V\n\025msg_f" +
      "wd_data_req_body\022\017\n\007data_id\030\001 \001(\t\022\014\n\004dat" +
      "a\030\002 \001(\014\022\r\n\005proto\030\003 \001(\t\022\017\n\007address\030\004 \001(\t\"" +
      "J\n\025msg_fwd_data_rsp_body\022\017\n\007data_id\030\001 \001(" +
      "\t\022\014\n\004data\030\002 \001(\014\022\022\n\nerror_code\030\003 \001(\005\"\275\001\n\025" +
      "msg_fwd_operator_body\022\025\n\roperator_type\030\001" +
      " \001(\t\022?\n\021fwd_data_req_body\030$ \001(\0132\".justic" +
      "e.net.msg_fwd_data_req_bodyH\000\022?\n\021fwd_dat" +
      "a_rsp_body\030% \001(\0132\".justice.net.msg_fwd_d" +
      "ata_rsp_bodyH\000B\013\n\tfunc_bodyB!\n\037com.lnjoy" +
      "ing.justice.schema.msgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_justice_net_msg_fwd_data_req_body_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_justice_net_msg_fwd_data_req_body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_justice_net_msg_fwd_data_req_body_descriptor,
        new java.lang.String[] { "DataId", "Data", "Proto", "Address", });
    internal_static_justice_net_msg_fwd_data_rsp_body_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_justice_net_msg_fwd_data_rsp_body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_justice_net_msg_fwd_data_rsp_body_descriptor,
        new java.lang.String[] { "DataId", "Data", "ErrorCode", });
    internal_static_justice_net_msg_fwd_operator_body_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_justice_net_msg_fwd_operator_body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_justice_net_msg_fwd_operator_body_descriptor,
        new java.lang.String[] { "OperatorType", "FwdDataReqBody", "FwdDataRspBody", "FuncBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
