/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * BoolConfigItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class BoolConfigItem
{
    @JsonProperty("editable")
    private Boolean editable = null;

    @JsonProperty("value")
    private Boolean value = null;

    public BoolConfigItem editable(Boolean editable)
    {
        this.editable = editable;
        return this;
    }

    /**
     * The configure item can be updated or not
     *
     * @return editable
     **/
    @ApiModelProperty(value = "The configure item can be updated or not")
    public Boolean isEditable()
    {
        return editable;
    }

    public void setEditable(Boolean editable)
    {
        this.editable = editable;
    }

    public BoolConfigItem value(Boolean value)
    {
        this.value = value;
        return this;
    }

    /**
     * The boolean value of current config item
     *
     * @return value
     **/
    @ApiModelProperty(value = "The boolean value of current config item")
    public Boolean isValue()
    {
        return value;
    }

    public void setValue(Boolean value)
    {
        this.value = value;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        BoolConfigItem boolConfigItem = (BoolConfigItem) o;
        return Objects.equals(this.editable, boolConfigItem.editable) &&
                Objects.equals(this.value, boolConfigItem.value);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(editable, value);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class BoolConfigItem {\n");

        sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

