/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * Icon
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class Icon
{
    @JsonProperty("content")
    private String content = null;

    @JsonProperty("content-type")
    private String contentType = null;

    public Icon content(String content)
    {
        this.content = content;
        return this;
    }

    /**
     * The base64 encoded content of the icon
     *
     * @return content
     **/
    @ApiModelProperty(value = "The base64 encoded content of the icon")
    public String getContent()
    {
        return content;
    }

    public void setContent(String content)
    {
        this.content = content;
    }

    public Icon contentType(String contentType)
    {
        this.contentType = contentType;
        return this;
    }

    /**
     * The content type of the icon
     *
     * @return contentType
     **/
    @ApiModelProperty(value = "The content type of the icon")
    public String getContentType()
    {
        return contentType;
    }

    public void setContentType(String contentType)
    {
        this.contentType = contentType;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        Icon icon = (Icon) o;
        return Objects.equals(this.content, icon.content) &&
                Objects.equals(this.contentType, icon.contentType);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(content, contentType);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class Icon {\n");

        sb.append("    content: ").append(toIndentedString(content)).append("\n");
        sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

