/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * LdapFailedImportUser
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class LdapFailedImportUser
{
    @JsonProperty("uid")
    private String uid = null;

    @JsonProperty("error")
    private String error = null;

    public LdapFailedImportUser uid(String uid)
    {
        this.uid = uid;
        return this;
    }

    /**
     * the uid can&#39;t add to system.
     *
     * @return uid
     **/
    @ApiModelProperty(value = "the uid can't add to system.")
    public String getUid()
    {
        return uid;
    }

    public void setUid(String uid)
    {
        this.uid = uid;
    }

    public LdapFailedImportUser error(String error)
    {
        this.error = error;
        return this;
    }

    /**
     * fail reason.
     *
     * @return error
     **/
    @ApiModelProperty(value = "fail reason.")
    public String getError()
    {
        return error;
    }

    public void setError(String error)
    {
        this.error = error;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        LdapFailedImportUser ldapFailedImportUser = (LdapFailedImportUser) o;
        return Objects.equals(this.uid, ldapFailedImportUser.uid) &&
                Objects.equals(this.error, ldapFailedImportUser.error);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(uid, error);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class LdapFailedImportUser {\n");

        sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
        sb.append("    error: ").append(toIndentedString(error)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

