/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * PasswordReq
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class PasswordReq
{
    @JsonProperty("new_password")
    private String newPassword = null;

    @JsonProperty("old_password")
    private String oldPassword = null;

    public PasswordReq newPassword(String newPassword)
    {
        this.newPassword = newPassword;
        return this;
    }

    /**
     * New password for marking as to be updated.
     *
     * @return newPassword
     **/
    @ApiModelProperty(value = "New password for marking as to be updated.")
    public String getNewPassword()
    {
        return newPassword;
    }

    public void setNewPassword(String newPassword)
    {
        this.newPassword = newPassword;
    }

    public PasswordReq oldPassword(String oldPassword)
    {
        this.oldPassword = oldPassword;
        return this;
    }

    /**
     * The user&#39;s existing password.
     *
     * @return oldPassword
     **/
    @ApiModelProperty(value = "The user's existing password.")
    public String getOldPassword()
    {
        return oldPassword;
    }

    public void setOldPassword(String oldPassword)
    {
        this.oldPassword = oldPassword;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        PasswordReq passwordReq = (PasswordReq) o;
        return Objects.equals(this.newPassword, passwordReq.newPassword) &&
                Objects.equals(this.oldPassword, passwordReq.oldPassword);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(newPassword, oldPassword);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class PasswordReq {\n");

        sb.append("    newPassword: ").append(toIndentedString(newPassword)).append("\n");
        sb.append("    oldPassword: ").append(toIndentedString(oldPassword)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

