/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * ProjectDeletable
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class ProjectDeletable
{
    @JsonProperty("message")
    private String message = null;

    @JsonProperty("deletable")
    private Boolean deletable = null;

    public ProjectDeletable message(String message)
    {
        this.message = message;
        return this;
    }

    /**
     * The detail message when the project can not be deleted.
     *
     * @return message
     **/
    @ApiModelProperty(value = "The detail message when the project can not be deleted.")
    public String getMessage()
    {
        return message;
    }

    public void setMessage(String message)
    {
        this.message = message;
    }

    public ProjectDeletable deletable(Boolean deletable)
    {
        this.deletable = deletable;
        return this;
    }

    /**
     * Whether the project can be deleted.
     *
     * @return deletable
     **/
    @ApiModelProperty(value = "Whether the project can be deleted.")
    public Boolean isDeletable()
    {
        return deletable;
    }

    public void setDeletable(Boolean deletable)
    {
        this.deletable = deletable;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        ProjectDeletable projectDeletable = (ProjectDeletable) o;
        return Objects.equals(this.message, projectDeletable.message) &&
                Objects.equals(this.deletable, projectDeletable.deletable);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(message, deletable);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProjectDeletable {\n");

        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    deletable: ").append(toIndentedString(deletable)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

