/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * ProviderUnderProject
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class ProviderUnderProject
{
    @JsonProperty("default")
    private Boolean _default = null;

    @JsonProperty("enabled")
    private Boolean enabled = null;

    @JsonProperty("id")
    private Integer id = null;

    @JsonProperty("provider")
    private String provider = null;

    public ProviderUnderProject _default(Boolean _default)
    {
        this._default = _default;
        return this;
    }

    /**
     * Get _default
     *
     * @return _default
     **/
    @ApiModelProperty(value = "")
    public Boolean isDefault()
    {
        return _default;
    }

    public void setDefault(Boolean _default)
    {
        this._default = _default;
    }

    public ProviderUnderProject enabled(Boolean enabled)
    {
        this.enabled = enabled;
        return this;
    }

    /**
     * Get enabled
     *
     * @return enabled
     **/
    @ApiModelProperty(value = "")
    public Boolean isEnabled()
    {
        return enabled;
    }

    public void setEnabled(Boolean enabled)
    {
        this.enabled = enabled;
    }

    public ProviderUnderProject id(Integer id)
    {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(value = "")
    public Integer getId()
    {
        return id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    public ProviderUnderProject provider(String provider)
    {
        this.provider = provider;
        return this;
    }

    /**
     * Get provider
     *
     * @return provider
     **/
    @ApiModelProperty(value = "")
    public String getProvider()
    {
        return provider;
    }

    public void setProvider(String provider)
    {
        this.provider = provider;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        ProviderUnderProject providerUnderProject = (ProviderUnderProject) o;
        return Objects.equals(this._default, providerUnderProject._default) &&
                Objects.equals(this.enabled, providerUnderProject.enabled) &&
                Objects.equals(this.id, providerUnderProject.id) &&
                Objects.equals(this.provider, providerUnderProject.provider);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(_default, enabled, id, provider);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProviderUnderProject {\n");

        sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
        sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

