/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * QuotaUpdateReq
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class QuotaUpdateReq
{
    @JsonProperty("hard")
    private ResourceList hard = null;

    public QuotaUpdateReq hard(ResourceList hard)
    {
        this.hard = hard;
        return this;
    }

    /**
     * The new hard limits for the quota
     *
     * @return hard
     **/
    @ApiModelProperty(value = "The new hard limits for the quota")
    public ResourceList getHard()
    {
        return hard;
    }

    public void setHard(ResourceList hard)
    {
        this.hard = hard;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        QuotaUpdateReq quotaUpdateReq = (QuotaUpdateReq) o;
        return Objects.equals(this.hard, quotaUpdateReq.hard);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(hard);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class QuotaUpdateReq {\n");

        sb.append("    hard: ").append(toIndentedString(hard)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

