/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * Reference
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class Reference
{
    @JsonProperty("platform")
    private Platform platform = null;

    @JsonProperty("child_digest")
    private String childDigest = null;

    @JsonProperty("urls")
    private List<String> urls = null;

    @JsonProperty("parent_id")
    private Long parentId = null;

    @JsonProperty("child_id")
    private Long childId = null;

    @JsonProperty("annotations")
    private Annotations annotations = null;

    public Reference platform(Platform platform)
    {
        this.platform = platform;
        return this;
    }

    /**
     * Get platform
     *
     * @return platform
     **/
    @ApiModelProperty(value = "")
    public Platform getPlatform()
    {
        return platform;
    }

    public void setPlatform(Platform platform)
    {
        this.platform = platform;
    }

    public Reference childDigest(String childDigest)
    {
        this.childDigest = childDigest;
        return this;
    }

    /**
     * The digest of the child artifact
     *
     * @return childDigest
     **/
    @ApiModelProperty(value = "The digest of the child artifact")
    public String getChildDigest()
    {
        return childDigest;
    }

    public void setChildDigest(String childDigest)
    {
        this.childDigest = childDigest;
    }

    public Reference urls(List<String> urls)
    {
        this.urls = urls;
        return this;
    }

    public Reference addUrlsItem(String urlsItem)
    {
        if (this.urls == null)
        {
            this.urls = new ArrayList<>();
        }
        this.urls.add(urlsItem);
        return this;
    }

    /**
     * The download URLs
     *
     * @return urls
     **/
    @ApiModelProperty(value = "The download URLs")
    public List<String> getUrls()
    {
        return urls;
    }

    public void setUrls(List<String> urls)
    {
        this.urls = urls;
    }

    public Reference parentId(Long parentId)
    {
        this.parentId = parentId;
        return this;
    }

    /**
     * The parent ID of the reference
     *
     * @return parentId
     **/
    @ApiModelProperty(value = "The parent ID of the reference")
    public Long getParentId()
    {
        return parentId;
    }

    public void setParentId(Long parentId)
    {
        this.parentId = parentId;
    }

    public Reference childId(Long childId)
    {
        this.childId = childId;
        return this;
    }

    /**
     * The child ID of the reference
     *
     * @return childId
     **/
    @ApiModelProperty(value = "The child ID of the reference")
    public Long getChildId()
    {
        return childId;
    }

    public void setChildId(Long childId)
    {
        this.childId = childId;
    }

    public Reference annotations(Annotations annotations)
    {
        this.annotations = annotations;
        return this;
    }

    /**
     * Get annotations
     *
     * @return annotations
     **/
    @ApiModelProperty(value = "")
    public Annotations getAnnotations()
    {
        return annotations;
    }

    public void setAnnotations(Annotations annotations)
    {
        this.annotations = annotations;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        Reference reference = (Reference) o;
        return Objects.equals(this.platform, reference.platform) &&
                Objects.equals(this.childDigest, reference.childDigest) &&
                Objects.equals(this.urls, reference.urls) &&
                Objects.equals(this.parentId, reference.parentId) &&
                Objects.equals(this.childId, reference.childId) &&
                Objects.equals(this.annotations, reference.annotations);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(platform, childDigest, urls, parentId, childId, annotations);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class Reference {\n");

        sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
        sb.append("    childDigest: ").append(toIndentedString(childDigest)).append("\n");
        sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
        sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
        sb.append("    childId: ").append(toIndentedString(childId)).append("\n");
        sb.append("    annotations: ").append(toIndentedString(annotations)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

