/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The style of the resource filter
 */
@ApiModel(description = "The style of the resource filter")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class RegistryEndpoint
{
    @JsonProperty("key")
    private String key = null;

    @JsonProperty("value")
    private String value = null;

    public RegistryEndpoint key(String key)
    {
        this.key = key;
        return this;
    }

    /**
     * The endpoint key
     *
     * @return key
     **/
    @ApiModelProperty(value = "The endpoint key")
    public String getKey()
    {
        return key;
    }

    public void setKey(String key)
    {
        this.key = key;
    }

    public RegistryEndpoint value(String value)
    {
        this.value = value;
        return this;
    }

    /**
     * The endpoint value
     *
     * @return value
     **/
    @ApiModelProperty(value = "The endpoint value")
    public String getValue()
    {
        return value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        RegistryEndpoint registryEndpoint = (RegistryEndpoint) o;
        return Objects.equals(this.key, registryEndpoint.key) &&
                Objects.equals(this.value, registryEndpoint.value);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(key, value);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class RegistryEndpoint {\n");

        sb.append("    key: ").append(toIndentedString(key)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

