/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * RetentionPolicyScope
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class RetentionPolicyScope
{
    @JsonProperty("ref")
    private Integer ref = null;

    @JsonProperty("level")
    private String level = null;

    public RetentionPolicyScope ref(Integer ref)
    {
        this.ref = ref;
        return this;
    }

    /**
     * Get ref
     *
     * @return ref
     **/
    @ApiModelProperty(value = "")
    public Integer getRef()
    {
        return ref;
    }

    public void setRef(Integer ref)
    {
        this.ref = ref;
    }

    public RetentionPolicyScope level(String level)
    {
        this.level = level;
        return this;
    }

    /**
     * Get level
     *
     * @return level
     **/
    @ApiModelProperty(value = "")
    public String getLevel()
    {
        return level;
    }

    public void setLevel(String level)
    {
        this.level = level;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        RetentionPolicyScope retentionPolicyScope = (RetentionPolicyScope) o;
        return Objects.equals(this.ref, retentionPolicyScope.ref) &&
                Objects.equals(this.level, retentionPolicyScope.level);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(ref, level);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class RetentionPolicyScope {\n");

        sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
        sb.append("    level: ").append(toIndentedString(level)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

