/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * rule param
 */
@ApiModel(description = "rule param")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class RetentionRuleParamMetadata
{
    @JsonProperty("required")
    private Boolean required = null;

    @JsonProperty("type")
    private String type = null;

    @JsonProperty("unit")
    private String unit = null;

    public RetentionRuleParamMetadata required(Boolean required)
    {
        this.required = required;
        return this;
    }

    /**
     * Get required
     *
     * @return required
     **/
    @ApiModelProperty(value = "")
    public Boolean isRequired()
    {
        return required;
    }

    public void setRequired(Boolean required)
    {
        this.required = required;
    }

    public RetentionRuleParamMetadata type(String type)
    {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @ApiModelProperty(value = "")
    public String getType()
    {
        return type;
    }

    public void setType(String type)
    {
        this.type = type;
    }

    public RetentionRuleParamMetadata unit(String unit)
    {
        this.unit = unit;
        return this;
    }

    /**
     * Get unit
     *
     * @return unit
     **/
    @ApiModelProperty(value = "")
    public String getUnit()
    {
        return unit;
    }

    public void setUnit(String unit)
    {
        this.unit = unit;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        RetentionRuleParamMetadata retentionRuleParamMetadata = (RetentionRuleParamMetadata) o;
        return Objects.equals(this.required, retentionRuleParamMetadata.required) &&
                Objects.equals(this.type, retentionRuleParamMetadata.type) &&
                Objects.equals(this.unit, retentionRuleParamMetadata.unit);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(required, type, unit);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class RetentionRuleParamMetadata {\n");

        sb.append("    required: ").append(toIndentedString(required)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

