/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * RetentionExecution
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class RetentionExecution
{
    @JsonProperty("status")
    private String status = null;

    @JsonProperty("trigger")
    private String trigger = null;

    @JsonProperty("end_time")
    private String endTime = null;

    @JsonProperty("dry_run")
    private Boolean dryRun = null;

    @JsonProperty("start_time")
    private String startTime = null;

    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("policy_id")
    private Long policyId = null;

    public RetentionExecution status(String status)
    {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/
    @ApiModelProperty(value = "")
    public String getStatus()
    {
        return status;
    }

    public void setStatus(String status)
    {
        this.status = status;
    }

    public RetentionExecution trigger(String trigger)
    {
        this.trigger = trigger;
        return this;
    }

    /**
     * Get trigger
     *
     * @return trigger
     **/
    @ApiModelProperty(value = "")
    public String getTrigger()
    {
        return trigger;
    }

    public void setTrigger(String trigger)
    {
        this.trigger = trigger;
    }

    public RetentionExecution endTime(String endTime)
    {
        this.endTime = endTime;
        return this;
    }

    /**
     * Get endTime
     *
     * @return endTime
     **/
    @ApiModelProperty(value = "")
    public String getEndTime()
    {
        return endTime;
    }

    public void setEndTime(String endTime)
    {
        this.endTime = endTime;
    }

    public RetentionExecution dryRun(Boolean dryRun)
    {
        this.dryRun = dryRun;
        return this;
    }

    /**
     * Get dryRun
     *
     * @return dryRun
     **/
    @ApiModelProperty(value = "")
    public Boolean isDryRun()
    {
        return dryRun;
    }

    public void setDryRun(Boolean dryRun)
    {
        this.dryRun = dryRun;
    }

    public RetentionExecution startTime(String startTime)
    {
        this.startTime = startTime;
        return this;
    }

    /**
     * Get startTime
     *
     * @return startTime
     **/
    @ApiModelProperty(value = "")
    public String getStartTime()
    {
        return startTime;
    }

    public void setStartTime(String startTime)
    {
        this.startTime = startTime;
    }

    public RetentionExecution id(Long id)
    {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(value = "")
    public Long getId()
    {
        return id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public RetentionExecution policyId(Long policyId)
    {
        this.policyId = policyId;
        return this;
    }

    /**
     * Get policyId
     *
     * @return policyId
     **/
    @ApiModelProperty(value = "")
    public Long getPolicyId()
    {
        return policyId;
    }

    public void setPolicyId(Long policyId)
    {
        this.policyId = policyId;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        RetentionExecution retentionExecution = (RetentionExecution) o;
        return Objects.equals(this.status, retentionExecution.status) &&
                Objects.equals(this.trigger, retentionExecution.trigger) &&
                Objects.equals(this.endTime, retentionExecution.endTime) &&
                Objects.equals(this.dryRun, retentionExecution.dryRun) &&
                Objects.equals(this.startTime, retentionExecution.startTime) &&
                Objects.equals(this.id, retentionExecution.id) &&
                Objects.equals(this.policyId, retentionExecution.policyId);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(status, trigger, endTime, dryRun, startTime, id, policyId);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class RetentionExecution {\n");

        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    trigger: ").append(toIndentedString(trigger)).append("\n");
        sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
        sb.append("    dryRun: ").append(toIndentedString(dryRun)).append("\n");
        sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

