/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * The response for robot account creation.
 */
@ApiModel(description = "The response for robot account creation.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class RobotCreated
{
    @JsonProperty("secret")
    private String secret = null;

    @JsonProperty("creation_time")
    private OffsetDateTime creationTime = null;

    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("expires_at")
    private Long expiresAt = null;

    @JsonProperty("name")
    private String name = null;

    public RobotCreated secret(String secret)
    {
        this.secret = secret;
        return this;
    }

    /**
     * The secret of the robot
     *
     * @return secret
     **/
    @ApiModelProperty(value = "The secret of the robot")
    public String getSecret()
    {
        return secret;
    }

    public void setSecret(String secret)
    {
        this.secret = secret;
    }

    public RobotCreated creationTime(OffsetDateTime creationTime)
    {
        this.creationTime = creationTime;
        return this;
    }

    /**
     * The creation time of the robot.
     *
     * @return creationTime
     **/
    @ApiModelProperty(value = "The creation time of the robot.")
    public OffsetDateTime getCreationTime()
    {
        return creationTime;
    }

    public void setCreationTime(OffsetDateTime creationTime)
    {
        this.creationTime = creationTime;
    }

    public RobotCreated id(Long id)
    {
        this.id = id;
        return this;
    }

    /**
     * The ID of the robot
     *
     * @return id
     **/
    @ApiModelProperty(value = "The ID of the robot")
    public Long getId()
    {
        return id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public RobotCreated expiresAt(Long expiresAt)
    {
        this.expiresAt = expiresAt;
        return this;
    }

    /**
     * The expiration data of the robot
     *
     * @return expiresAt
     **/
    @ApiModelProperty(value = "The expiration data of the robot")
    public Long getExpiresAt()
    {
        return expiresAt;
    }

    public void setExpiresAt(Long expiresAt)
    {
        this.expiresAt = expiresAt;
    }

    public RobotCreated name(String name)
    {
        this.name = name;
        return this;
    }

    /**
     * The name of the tag
     *
     * @return name
     **/
    @ApiModelProperty(value = "The name of the tag")
    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        RobotCreated robotCreated = (RobotCreated) o;
        return Objects.equals(this.secret, robotCreated.secret) &&
                Objects.equals(this.creationTime, robotCreated.creationTime) &&
                Objects.equals(this.id, robotCreated.id) &&
                Objects.equals(this.expiresAt, robotCreated.expiresAt) &&
                Objects.equals(this.name, robotCreated.name);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(secret, creationTime, id, expiresAt, name);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class RobotCreated {\n");

        sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
        sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

