/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * UserResp
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class UserResp
{
    @JsonProperty("comment")
    private String comment = null;

    @JsonProperty("username")
    private String username = null;

    @JsonProperty("update_time")
    private OffsetDateTime updateTime = null;

    @JsonProperty("user_id")
    private Integer userId = null;

    @JsonProperty("realname")
    private String realname = null;

    @JsonProperty("oidc_user_meta")
    private OIDCUserInfo oidcUserMeta = null;

    @JsonProperty("creation_time")
    private OffsetDateTime creationTime = null;

    @JsonProperty("admin_role_in_auth")
    private Boolean adminRoleInAuth = null;

    @JsonProperty("sysadmin_flag")
    private Boolean sysadminFlag = null;

    @JsonProperty("email")
    private String email = null;

    public UserResp comment(String comment)
    {
        this.comment = comment;
        return this;
    }

    /**
     * Get comment
     *
     * @return comment
     **/
    @ApiModelProperty(value = "")
    public String getComment()
    {
        return comment;
    }

    public void setComment(String comment)
    {
        this.comment = comment;
    }

    public UserResp username(String username)
    {
        this.username = username;
        return this;
    }

    /**
     * Get username
     *
     * @return username
     **/
    @ApiModelProperty(value = "")
    public String getUsername()
    {
        return username;
    }

    public void setUsername(String username)
    {
        this.username = username;
    }

    public UserResp updateTime(OffsetDateTime updateTime)
    {
        this.updateTime = updateTime;
        return this;
    }

    /**
     * The update time of the user.
     *
     * @return updateTime
     **/
    @ApiModelProperty(value = "The update time of the user.")
    public OffsetDateTime getUpdateTime()
    {
        return updateTime;
    }

    public void setUpdateTime(OffsetDateTime updateTime)
    {
        this.updateTime = updateTime;
    }

    public UserResp userId(Integer userId)
    {
        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     *
     * @return userId
     **/
    @ApiModelProperty(value = "")
    public Integer getUserId()
    {
        return userId;
    }

    public void setUserId(Integer userId)
    {
        this.userId = userId;
    }

    public UserResp realname(String realname)
    {
        this.realname = realname;
        return this;
    }

    /**
     * Get realname
     *
     * @return realname
     **/
    @ApiModelProperty(value = "")
    public String getRealname()
    {
        return realname;
    }

    public void setRealname(String realname)
    {
        this.realname = realname;
    }

    public UserResp oidcUserMeta(OIDCUserInfo oidcUserMeta)
    {
        this.oidcUserMeta = oidcUserMeta;
        return this;
    }

    /**
     * Get oidcUserMeta
     *
     * @return oidcUserMeta
     **/
    @ApiModelProperty(value = "")
    public OIDCUserInfo getOidcUserMeta()
    {
        return oidcUserMeta;
    }

    public void setOidcUserMeta(OIDCUserInfo oidcUserMeta)
    {
        this.oidcUserMeta = oidcUserMeta;
    }

    public UserResp creationTime(OffsetDateTime creationTime)
    {
        this.creationTime = creationTime;
        return this;
    }

    /**
     * The creation time of the user.
     *
     * @return creationTime
     **/
    @ApiModelProperty(value = "The creation time of the user.")
    public OffsetDateTime getCreationTime()
    {
        return creationTime;
    }

    public void setCreationTime(OffsetDateTime creationTime)
    {
        this.creationTime = creationTime;
    }

    public UserResp adminRoleInAuth(Boolean adminRoleInAuth)
    {
        this.adminRoleInAuth = adminRoleInAuth;
        return this;
    }

    /**
     * indicate the admin privilege is grant by authenticator (LDAP), is always false unless it is the current login user
     *
     * @return adminRoleInAuth
     **/
    @ApiModelProperty(value = "indicate the admin privilege is grant by authenticator (LDAP), is always false unless it is the current login user")
    public Boolean isAdminRoleInAuth()
    {
        return adminRoleInAuth;
    }

    public void setAdminRoleInAuth(Boolean adminRoleInAuth)
    {
        this.adminRoleInAuth = adminRoleInAuth;
    }

    public UserResp sysadminFlag(Boolean sysadminFlag)
    {
        this.sysadminFlag = sysadminFlag;
        return this;
    }

    /**
     * Get sysadminFlag
     *
     * @return sysadminFlag
     **/
    @ApiModelProperty(value = "")
    public Boolean isSysadminFlag()
    {
        return sysadminFlag;
    }

    public void setSysadminFlag(Boolean sysadminFlag)
    {
        this.sysadminFlag = sysadminFlag;
    }

    public UserResp email(String email)
    {
        this.email = email;
        return this;
    }

    /**
     * Get email
     *
     * @return email
     **/
    @ApiModelProperty(value = "")
    public String getEmail()
    {
        return email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        UserResp userResp = (UserResp) o;
        return Objects.equals(this.comment, userResp.comment) &&
                Objects.equals(this.username, userResp.username) &&
                Objects.equals(this.updateTime, userResp.updateTime) &&
                Objects.equals(this.userId, userResp.userId) &&
                Objects.equals(this.realname, userResp.realname) &&
                Objects.equals(this.oidcUserMeta, userResp.oidcUserMeta) &&
                Objects.equals(this.creationTime, userResp.creationTime) &&
                Objects.equals(this.adminRoleInAuth, userResp.adminRoleInAuth) &&
                Objects.equals(this.sysadminFlag, userResp.sysadminFlag) &&
                Objects.equals(this.email, userResp.email);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(comment, username, updateTime, userId, realname, oidcUserMeta, creationTime, adminRoleInAuth, sysadminFlag, email);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserResp {\n");

        sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
        sb.append("    username: ").append(toIndentedString(username)).append("\n");
        sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    realname: ").append(toIndentedString(realname)).append("\n");
        sb.append("    oidcUserMeta: ").append(toIndentedString(oidcUserMeta)).append("\n");
        sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
        sb.append("    adminRoleInAuth: ").append(toIndentedString(adminRoleInAuth)).append("\n");
        sb.append("    sysadminFlag: ").append(toIndentedString(sysadminFlag)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

