/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lnjoying.justice.ims.harbor.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * The webhook policy and last trigger time group by event type.
 */
@ApiModel(description = "The webhook policy and last trigger time group by event type.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-31T16:17:12.981+08:00")
public class WebhookLastTrigger
{
    @JsonProperty("enabled")
    private Boolean enabled = null;

    @JsonProperty("creation_time")
    private OffsetDateTime creationTime = null;

    @JsonProperty("event_type")
    private String eventType = null;

    @JsonProperty("last_trigger_time")
    private OffsetDateTime lastTriggerTime = null;

    @JsonProperty("policy_name")
    private String policyName = null;

    public WebhookLastTrigger enabled(Boolean enabled)
    {
        this.enabled = enabled;
        return this;
    }

    /**
     * Whether or not the webhook policy enabled.
     *
     * @return enabled
     **/
    @ApiModelProperty(value = "Whether or not the webhook policy enabled.")
    public Boolean isEnabled()
    {
        return enabled;
    }

    public void setEnabled(Boolean enabled)
    {
        this.enabled = enabled;
    }

    public WebhookLastTrigger creationTime(OffsetDateTime creationTime)
    {
        this.creationTime = creationTime;
        return this;
    }

    /**
     * The creation time of webhook policy.
     *
     * @return creationTime
     **/
    @ApiModelProperty(value = "The creation time of webhook policy.")
    public OffsetDateTime getCreationTime()
    {
        return creationTime;
    }

    public void setCreationTime(OffsetDateTime creationTime)
    {
        this.creationTime = creationTime;
    }

    public WebhookLastTrigger eventType(String eventType)
    {
        this.eventType = eventType;
        return this;
    }

    /**
     * The webhook event type.
     *
     * @return eventType
     **/
    @ApiModelProperty(value = "The webhook event type.")
    public String getEventType()
    {
        return eventType;
    }

    public void setEventType(String eventType)
    {
        this.eventType = eventType;
    }

    public WebhookLastTrigger lastTriggerTime(OffsetDateTime lastTriggerTime)
    {
        this.lastTriggerTime = lastTriggerTime;
        return this;
    }

    /**
     * The last trigger time of webhook policy.
     *
     * @return lastTriggerTime
     **/
    @ApiModelProperty(value = "The last trigger time of webhook policy.")
    public OffsetDateTime getLastTriggerTime()
    {
        return lastTriggerTime;
    }

    public void setLastTriggerTime(OffsetDateTime lastTriggerTime)
    {
        this.lastTriggerTime = lastTriggerTime;
    }

    public WebhookLastTrigger policyName(String policyName)
    {
        this.policyName = policyName;
        return this;
    }

    /**
     * The webhook policy name.
     *
     * @return policyName
     **/
    @ApiModelProperty(value = "The webhook policy name.")
    public String getPolicyName()
    {
        return policyName;
    }

    public void setPolicyName(String policyName)
    {
        this.policyName = policyName;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        WebhookLastTrigger webhookLastTrigger = (WebhookLastTrigger) o;
        return Objects.equals(this.enabled, webhookLastTrigger.enabled) &&
                Objects.equals(this.creationTime, webhookLastTrigger.creationTime) &&
                Objects.equals(this.eventType, webhookLastTrigger.eventType) &&
                Objects.equals(this.lastTriggerTime, webhookLastTrigger.lastTriggerTime) &&
                Objects.equals(this.policyName, webhookLastTrigger.policyName);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(enabled, creationTime, eventType, lastTriggerTime, policyName);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class WebhookLastTrigger {\n");

        sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
        sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
        sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
        sb.append("    lastTriggerTime: ").append(toIndentedString(lastTriggerTime)).append("\n");
        sb.append("    policyName: ").append(toIndentedString(policyName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

