INSERT INTO "public"."tbl_label_option_info" ("key", "label_type", "type", "label_option", "order_num") VALUES ('com.justice.node/resource:gpu', 'node', 'label', '{"key":"com.justice.node/resource:gpu","show_name":"支持GPU类型","description":"支持GPU类型，无此标签则不支持，多个值时以“,”分隔。示例：nvidia","type":"string","required":false,"default_value":null,"options":[],"immutable":true}', 7);
INSERT INTO "public"."tbl_label_option_info" ("key", "label_type", "type", "label_option", "order_num") VALUES ('com.justice.site/resource:bandwidth', 'site', 'label', '{"key":"com.justice.site/resource:bandwidth","show_name":"带宽","description":"单个整数数值，单位Mbps。示例：100","type":"int","required":false,"default_value":0,"options":[],"immutable":true}', 2);
INSERT INTO "public"."tbl_label_option_info" ("key", "label_type", "type", "label_option", "order_num") VALUES ('com.justice.node/orchestration', 'node', 'label', '{"key":"com.justice.node/orchestration","description":"节点支持的编排类型，使用本节点部署集群时，需要更改编排类型为K8s","show_name":"编排类型","type":"enum","required":false,"default_value":"docker","options":["docker","k8s"],"immutable":true}', 3);
INSERT INTO "public"."tbl_label_option_info" ("key", "label_type", "type", "label_option", "order_num") VALUES ('com.justice.site/bpId', 'site', 'label', '{"key":"com.justice.site/bpId","description":"组织名称","show_name":"组织机构","type":"string","required":false,"default_value":null,"options":[],"immutable":true}', 1);
INSERT INTO "public"."tbl_label_option_info" ("key", "label_type", "type", "label_option", "order_num") VALUES ('com.justice.node/owner', 'node', 'label', '{"key":"com.justice.node/owner","description":null,"show_name":"所有者","type":"string","required":false,"default_value":null,"options":[],"immutable":true}', 2);
INSERT INTO "public"."tbl_label_option_info" ("key", "label_type", "type", "label_option", "order_num") VALUES ('com.justice.node/bpId', 'node', 'label', '{"key":"com.justice.node/bpId","description":"组织名称","show_name":"组织机构","type":"string","required":false,"default_value":null,"options":[],"immutable":true}', 1);
INSERT INTO "public"."tbl_label_option_info" ("key", "label_type", "type", "label_option", "order_num") VALUES ('com.justice.node/ip:external', 'node', 'label', '{"key":"com.justice.node/ip:external","description":"公网IP","show_name":"公网IP","type":"string","required":false,"default_value":null,"options":[],"immutable":true,"constraints":{"regex":"((2(5[0-5]|[0-4]\\d))|[0-1]?\\d{1,2})(\\.((2(5[0-5]|[0-4]\\d))|[0-1]?\\d{1,2})){3}"}}', 5);
INSERT INTO "public"."tbl_label_option_info" ("key", "label_type", "type", "label_option", "order_num") VALUES ('com.justice.node/ip:internal', 'node', 'label', '{"key":"com.justice.node/ip:internal","description":"内网IP","show_name":"内网IP","type":"string","required":false,"default_value":null,"options":[],"immutable":true,"constraints":{"regex":"((2(5[0-5]|[0-4]\\d))|[0-1]?\\d{1,2})(\\.((2(5[0-5]|[0-4]\\d))|[0-1]?\\d{1,2})){3}"}}', 6);
INSERT INTO "public"."tbl_label_option_info" ("key", "label_type", "type", "label_option", "order_num") VALUES ('com.justice.node/roles', 'node', 'label', '{"key":"com.justice.node/roles","description":"设备的角色","show_name":"设备的角色","type":"enum","required":false,"default_value":null,"options":["controller","etcd","worker","controller,etcd","etcd,worker","controller,worker","controller,etcd,worker"],"immutable":true}', 4);

INSERT INTO "public"."tbl_region_info" ("region_id", "region_name", "region_desc", "status", "create_time", "update_time", "labels", "taints") VALUES ('default', '默认', NULL, 1, '1970-01-01 00:00:00+08', '1970-01-01 00:00:00+08', '{}', '{}');
INSERT INTO "public"."tbl_site_info" ("site_id", "region_id", "site_name", "site_location", "site_desc", "scope", "user_id", "bp_id", "adcode", "status", "create_time", "update_time", "labels", "taints") VALUES ('default', 'default', '默认', '{"nation":"","address":"\u0026,,,","adcode":"","longitude":0.0,"latitude":0.0,"elevation":0.0,"detail_address":""}', NULL, NULL, NULL, NULL, '', 1, '1970-01-01 00:00:00+08', '1970-01-01 00:00:00+08', '{}', '{}');