INSERT INTO "public"."tbl_repo_category_info" ("category_id", "category", "name", "key_word", "create_time", "update_time", "description") VALUES (1, 'Web Server', 'Web Server', '["nodejs","cms","crm","e-commerce","drupal","wordpress","http","phabricator","web","game","https","www","opencart","communication","storage","orangehrm","git","subversion","owncloud","javascript","chat","osclass","ruby","kubernetes job manager","code review","prestashop","application","mercurial","bug tracking","classifieds","rails","server","collaboration","magento","redmine","human resources","ghost","wiki","blog","dokuwiki","php","mediawiki","markdown","spark","dependency graph","luigi","scheduler","odoo","meteor","hadoop","nextcloud","task management","project management","hackmd"]', '2022-08-09 10:16:39+08', '2022-08-09 10:16:43+08', 'web');
INSERT INTO "public"."tbl_repo_category_info" ("category_id", "category", "name", "key_word", "create_time", "update_time", "description") VALUES (2, 'Message Queueing', 'Message Queueing', '["queue"]', '2022-08-09 10:17:01+08', '2022-08-09 10:17:04+08', 'message');
INSERT INTO "public"."tbl_repo_category_info" ("category_id", "category", "name", "key_word", "create_time", "update_time", "description") VALUES (3, 'storage', 'storage', '["object-storage","iSCSI","nfs","storage","cloud-native-storage","S3","block-storage"]', '2022-08-09 10:17:25+08', '2022-08-09 10:17:28+08', 'storage');
INSERT INTO "public"."tbl_repo_category_info" ("category_id", "category", "name", "key_word", "create_time", "update_time", "description") VALUES (4, 'Image Registry', 'Image Registry', '["scanner","analysis","image","anchore","vulnerability","docker","anchore-engine","security"]', '2022-08-09 10:18:11+08', '2022-08-09 10:18:15+08', 'image');
INSERT INTO "public"."tbl_repo_category_info" ("category_id", "category", "name", "key_word", "create_time", "update_time", "description") VALUES (5, 'Database & Cache', 'Database & Cache', '["cluster","memcached","prometheus","redis","galera","postgresql","timeseries","mysql","replication","google","key-value","xtradb","keyvalue","in-memory","mongodb","java","cache","nosql","wsrep","operator","mariadb","rethinkdb","couchdb","hazelcast","couchbase","caching","replicaset","distributed","cloud","database","jvm","sql","percona","postgres","influxdb","sqlproxy","datagrid"]', '2022-08-09 10:18:43+08', '2022-08-09 10:18:46+08', 'database');
INSERT INTO "public"."tbl_repo_category_info" ("category_id", "category", "name", "key_word", "create_time", "update_time", "description") VALUES (6, 'Networking', 'Networking', '["vpn","service","encryption","openvpn","connectivity","kubedns","tunnel","dns","external-dns","coredns","network"]', '2022-08-09 10:19:01+08', '2022-08-09 10:19:04+08', 'network');
INSERT INTO "public"."tbl_repo_category_info" ("category_id", "category", "name", "key_word", "create_time", "update_time", "description") VALUES (8, 'uncategorized', 'uncategorized', '[]', '2022-08-25 10:27:58+08', '2022-08-25 10:28:01+08', 'uncategorized');


ALTER TABLE "public"."tbl_stack_template_base_info"
    ADD COLUMN "scope" int4 DEFAULT 0;

COMMENT ON COLUMN "public"."tbl_stack_template_base_info"."scope" IS 'scope(0:private;1:bp;2:public)';