{
 "title": "lnjoying cadvisor exporter",
 "description": "Docker 容器指标. (cAdvisor/Prometheus)",
 "tags": [
  "service_light_node",
  "omc",
  "container"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "bp",
    "label": "组织",
    "query": {
     "query": "label_values(container_label_JDS_BPID)"
    }
   },
   {
    "name": "user",
    "label": "用户",
    "query": {
     "query": "label_values({container_label_JDS_BPID=\"$bp\"},container_label_JDS_UID)"
    }
   },
   { "name": "node_id", "label": "节点", "query": { "query": "label_values(node_id)" } },
   {
    "name": "container_name",
    "label": "容器",
    "query": {
     "query": "label_values({container_label_JDS_BPID=~\"$bp\", container_label_JDS_UID=~\"$user\",container_ref_id=~\"$container_ref_id\", container_label_JDS_BPID=~\"$bp\",container_label_JDS_UID=~\"$user\",container_ref_id=~\"$container_ref_id\",node_id=~\"$node_id\"},name)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "container_ref_id", "label": "container_ref_id", "query": { "query": "label_values(container_ref_id)" } }
  ]
 },
 "panels": [
  {
   "title": "运行中的容器数量",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "count(container_last_seen{container_label_JDS_BPID=~\"$bp\",container_label_JDS_UID=~\"$user\",container_ref_id=~\"$container_ref_id\",node_id=~\"$node_id\",image=~\"(.)+\"})",
     "legendFormat": "__auto",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "count(container_last_seen{container_label_JDS_BPID=~\"$bp\",container_label_JDS_UID=~\"$user\",container_ref_id=~\"$container_ref_id\",node_id=~\"$node_id\",job=~\"$job\",image!=\"\"})",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "节点上的CPU使用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{node_id=~\"$node_id\"}[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "节点上的网络流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_JDS_BPID=~\"$bp\",container_label_JDS_UID=~\"$user\",container_ref_id=~\"$container_ref_id\",node_id=~\"$node_id\",id!=\"\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{container_label_JDS_BPID=~\"$bp\",container_label_JDS_UID=~\"$user\",container_ref_id=~\"$container_ref_id\",node_id=~\"$node_id\",id!=\"\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "容器的缓存内存",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_cache{container_label_JDS_BPID=~\"$bp\",container_label_JDS_UID=~\"$user\",container_ref_id=~\"$container_ref_id\",node_id=~\"$node_id\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "容器的内存使用情况",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_label_JDS_BPID=~\"$bp\",container_label_JDS_UID=~\"$user\",container_ref_id=~\"$container_ref_id\",node_id=~\"$node_id\",name=~\"$container_name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "容器发送的网络流量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_JDS_BPID=~\"$bp\",container_label_JDS_UID=~\"$user\",container_ref_id=~\"$container_ref_id\",node_id=~\"$node_id\",name=~\"$container_name\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "容器的 CPU 使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_JDS_BPID=~\"$bp\",container_label_JDS_UID=~\"$user\",container_ref_id=~\"$container_ref_id\",node_id=~\"$node_id\",name=~\"$container_name\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "容器接收的网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_JDS_BPID=~\"$bp\",container_label_JDS_UID=~\"$user\",container_ref_id=~\"$container_ref_id\",node_id=~\"$node_id\",name=~\"$container_name\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "cadvisor_version_info{node_id=~\"$node_id\"}",
     "legendFormat": "cAdvisor Version: {{cadvisorVersion}}"
    },
    {
     "expr": "prometheus_build_info{}",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "node_exporter_build_info{node_id=~\"$node_id\"}",
     "legendFormat": "Node-Exporter Version: {{version}}"
    },
    {
     "expr": "cadvisor_version_info{node_id=~\"$node_id\"}",
     "legendFormat": "Docker Version: {{dockerVersion}}"
    },
    {
     "expr": "cadvisor_version_info{node_id=~\"$node_id\"}",
     "legendFormat": "Host OS Version: {{osVersion}}"
    },
    {
     "expr": "cadvisor_version_info{node_id=~\"$node_id\"}",
     "legendFormat": "Host Kernel Version: {{kernelVersion}}"
    }
   ]
  }
 ]
}