{
 "title": "Nvidia GPU",
 "description": "Nvidia GPU 指标基于 nvidia_gpu_exporter 的 prometheus 指标",
 "tags": [
  "nvidia",
  "nvidia-smi",
  "nvidia_gpu_exporter",
  "omc",
  "service_light_node",
  "resource_gpu"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node_id", "label": "节点", "query": { "query": "label_values(node_id)" } },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(nvidia_smi_index{node_id=\"$node_id\"},uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU名称",
   "type": "stat",
   "description": "GPU 的官方产品名称.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_gpu_info{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GPU 的性能状态",
   "type": "stat",
   "description": "GPU 的当前性能状态。 状态范围从 P0（最高性能）到 P12（最低性能）",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "prefix:P" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_pstate{uuid=\"$gpu\",node_id=\"$node_id\"}"
    }
   ]
  },
  {
   "title": "GPU利用率",
   "type": "gauge",
   "description": "过去采样周期内一个或多个内核在 GPU 上执行的时间百分比。\n采样周期可能介于 1 秒到 1/6 秒之间，具体取决于产品.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "功耗",
   "type": "gauge",
   "description": "最后测量的整个电路板的功耗（以瓦为单位）。 仅在支持电源管理时可用。 该读数精确到 +/- 5 瓦/软件功率限制（以瓦为单位）.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{uuid=\"$gpu\",node_id=\"$node_id\"} / nvidia_smi_power_default_limit_watts{uuid=\"$gpu\",node_id=\"$node_id\"}"
    }
   ]
  },
  {
   "title": "风扇转速",
   "type": "gauge",
   "description": "风扇速度值是设备风扇当前运行时的产品最大噪声容限风扇速度的百分比。 在某些情况下该值可能会超过 100%。 注意：报告的速度是预期的风扇速度。 如果风扇被物理堵塞并且无法旋转，则该输出将与实际风扇速度不匹配。 许多部件不报告风扇速度，因为它们依赖于周围外壳中的风扇进行冷却.\n",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed_ratio{uuid=\"$gpu\",node_id=\"$node_id\"}"
    }
   ]
  },
  {
   "title": "温度",
   "type": "gauge",
   "description": "核心 GPU 温度。 以摄氏度为单位.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "内存利用率",
   "type": "graph",
   "description": "读取或写入全局(设备)内存的过去采样周期的时间百分比。\n采样周期可能在 1 秒到 1/6 秒之间，具体取决于产品.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory_ratio{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "驱动版本",
   "type": "stat",
   "description": "已安装的 NVIDIA 显示驱动程序的版本.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_gpu_info{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{driver_version}}"
    }
   ]
  },
  {
   "title": "Vbios 版本",
   "type": "stat",
   "description": "GPU板的BIOS.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_gpu_info{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{vbios_version}}"
    }
   ]
  },
  {
   "title": "节流原因",
   "type": "bargauge",
   "description": "有关降低时钟频率的因素的信息。 如果所有节流原因都返回为“Not Active”，则意味着时钟运行得尽可能高.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_throttle_reasons_gpu_idle{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "nvidia_smi_clocks_throttle_reasons_hw_thermal_slowdown{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "HW Thermal Slowdown"
    },
    {
     "expr": "nvidia_smi_clocks_throttle_reasons_sw_power_cap{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "SW Power Cap"
    },
    {
     "expr": "nvidia_smi_clocks_throttle_reasons_applications_clocks_setting{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "App Clocks Setting"
    },
    {
     "expr": "nvidia_smi_clocks_throttle_reasons_hw_power_brake_slowdown{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "HW Power Brake"
    },
    {
     "expr": "nvidia_smi_clocks_throttle_reasons_sw_thermal_slowdown{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "SW Thermal Slowdown"
    },
    {
     "expr": "nvidia_smi_clocks_throttle_reasons_sync_boost{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "Sync Boost"
    }
   ]
  },
  {
   "title": "GPU 时钟速度",
   "type": "gauge",
   "description": "图形(着色器)时钟的当前频率\n/\n图形(着色器)时钟的最大频率.\n",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_graphics_clock_hz{uuid=\"$gpu\",node_id=\"$node_id\"} / nvidia_smi_clocks_max_graphics_clock_hz{uuid=\"$gpu\",node_id=\"$node_id\"}"
    }
   ]
  },
  {
   "title": "内存时钟速度",
   "type": "gauge",
   "description": "内存时钟当前频率/内存时钟最大频率",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_memory_clock_hz{uuid=\"$gpu\",node_id=\"$node_id\"} / nvidia_smi_clocks_max_memory_clock_hz{uuid=\"$gpu\",node_id=\"$node_id\"}"
    }
   ]
  },
  {
   "title": "内存分配",
   "type": "gauge",
   "description": "活动上下文分配的总内存/安装的 GPU 总内存.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes{uuid=\"$gpu\",node_id=\"$node_id\"} / nvidia_smi_memory_total_bytes{uuid=\"$gpu\",node_id=\"$node_id\"}"
    }
   ]
  },
  {
   "title": "内存利用率",
   "type": "gauge",
   "description": "读取或写入全局(设备)内存的过去采样周期的时间百分比。\n采样周期可能在 1 秒到 1/6 秒之间，具体取决于产品.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory_ratio{uuid=\"$gpu\",node_id=\"$node_id\"}"
    }
   ]
  },
  {
   "title": "GPU利用率",
   "type": "graph",
   "description": "过去采样周期内一个或多个内核在 GPU 上执行的时间百分比。\n采样周期可能介于 1 秒到 1/6 秒之间，具体取决于产品.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{uuid=\"$gpu\",node_id=\"$node_id\"}"
    }
   ]
  },
  {
   "title": "内存分配",
   "type": "graph",
   "description": "活动上下文分配的总内存.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "温度",
   "type": "graph",
   "description": "核心 GPU 温度。 以摄氏度为单位.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "功耗",
   "type": "graph",
   "description": "最后测量的整个电路板的功耗（以瓦为单位）。 仅在支持电源管理时可用。 该读数精确到 +/- 5 瓦以内",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "风扇转速",
   "type": "graph",
   "description": "风扇速度值是设备风扇当前运行时的产品最大噪声容限风扇速度的百分比。 在某些情况下该值可能会超过 100%。 注意：报告的速度是预期的风扇速度。 如果风扇被物理堵塞并且无法旋转，则该输出将与实际风扇速度不匹配。 许多部件不报告风扇速度，因为它们依赖于周围外壳中的风扇进行冷却.\n",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed_ratio{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "图形时钟速度",
   "type": "graph",
   "description": "图形（着色器）时钟的当前频率.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_graphics_clock_hz{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "视频时钟速度",
   "type": "graph",
   "description": "视频编码器/解码器时钟的当前频率.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_video_clock_hz{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "SM 时钟速度",
   "type": "graph",
   "description": "SM（流式多处理器）时钟的当前频率.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_sm_clock_hz{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "内存时钟速度",
   "type": "graph",
   "description": "内存时钟的当前频率.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_memory_clock_hz{uuid=\"$gpu\",node_id=\"$node_id\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}