{
 "title": "nextstack_gpu",
 "description": "Nvidia GPU Metrics based on the prometheus metrics from github.com/utkuozdemir/nvidia_gpu_exporter",
 "tags": [
  "omc",
  "nextstack",
  "gpu"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cloud_id", "label": "云", "query": { "query": "label_values(cloud_id)" } },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(nvidia_smi_gpu_info, uuid)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(nvidia_gpu_exporter_build_info{cloud_id=\"$cloud_id\"},instance)"
    }
   },
   {
    "name": "vm_name",
    "query": {
     "query": "label_values(nvidia_smi_gpu_info{instance=~\"$node\"}, instanceName)"
    }
   },
   {
    "name": "vm_instance_id",
    "query": {
     "query": "label_values(nvidia_smi_gpu_info{cloud_id=~\"$cloud_id\", instance=~\"$node\"},instanceId)"
    }
   },
   {
    "name": "vm_user_id",
    "query": {
     "query": "label_values(nvidia_smi_gpu_info{instance=~\"$node\"}, userId)"
    }
   },
   {
    "name": "gpu_index",
    "query": {
     "query": "query_result(nvidia_smi_index{uuid=~\"$gpu\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU设备",
   "type": "stat",
   "description": "The official product name of the GPU. This is an alphanumeric string. For all products.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_gpu_info{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}[12h]",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}:               {{name}}"
    }
   ]
  },
  {
   "title": "GPU显存总量",
   "type": "stat",
   "description": "GPU memory total_size",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(max_over_time(nvidia_smi_memory_total_bytes{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\" }[12h])/1000/1000/1000)",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}"
    }
   ]
  },
  {
   "title": "驱动版本",
   "type": "stat",
   "description": "The version of the installed NVIDIA display driver. This is an alphanumeric string.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_gpu_info{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}[12h]",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}:  {{driver_version}}"
    }
   ]
  },
  {
   "title": "GPU核心使用率",
   "type": "stat",
   "description": "GPU memory total_size",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}*100",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}"
    }
   ]
  },
  {
   "title": "GPU 使用率",
   "type": "timeseries",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}*100",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}"
    }
   ]
  },
  {
   "title": "GPU显存已用量",
   "type": "stat",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}"
    }
   ]
  },
  {
   "title": "GPU 显存使用率",
   "type": "timeseries",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory_ratio{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}*100",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}"
    }
   ]
  },
  {
   "title": "GPU 显存分配率",
   "type": "timeseries",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(nvidia_smi_memory_used_bytes{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}/nvidia_smi_memory_total_bytes{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}*100)",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}"
    }
   ]
  },
  {
   "title": "GPU功耗",
   "type": "stat",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}"
    }
   ]
  },
  {
   "title": "功耗统计",
   "type": "timeseries",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts / The software power limit in watts.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"} / nvidia_smi_power_default_limit_watts{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}"
    }
   ]
  },
  {
   "title": "GPU温度",
   "type": "stat",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}"
    }
   ]
  },
  {
   "title": "GPU峰值频率",
   "type": "stat",
   "description": "Current frequency of graphics (shader) clock.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_graphics_clock_hz{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",instance=~\"$node\",userId=~\"$vm_user_id\"}",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}"
    }
   ]
  },
  {
   "title": "GPU频率",
   "type": "stat",
   "description": "Current frequency of video encoder/decoder clock.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_video_clock_hz{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}"
    }
   ]
  },
  {
   "title": "风扇转速",
   "type": "timeseries",
   "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed_ratio{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceId=~\"$vm_instance_id\",instanceName=~\"$vm_name\",userId=~\"$vm_user_id\",instance=~\"$node\"}",
     "legendFormat": "{{instanceName}}_{{gpuIndex}}"
    }
   ]
  }
 ]
}