{
 "title": "nextstack_libvirt",
 "description": "\nhttps://github.com/ycy1766/prometheus-libvirt-exporter",
 "tags": [
  "libvirt",
  "nextstack ",
  "omc"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cloud_id", "label": "云", "query": { "query": "label_values(cloud_id)" } },
   { "name": "project_name", "query": { "query": "label_values(project_name)" } },
   {
    "name": "compute_node",
    "query": {
     "query": "label_values(libvirt_domain_info_memory_usage_bytes{project_name=\"$project_name\"}, instance)"
    }
   },
   {
    "name": "vm_name",
    "query": {
     "query": "label_values(libvirt_domain_info_memory_usage_bytes{project_name=\"$project_name\",instance=~\"$compute_node\"}, instanceName)"
    }
   },
   {
    "name": "vm_instance_id",
    "query": {
     "query": "label_values(libvirt_domain_info_memory_usage_bytes{project_name=\"$project_name\",instance=~\"$compute_node\"}, instanceId)"
    }
   },
   {
    "name": "vm_user_id",
    "query": {
     "query": "label_values(libvirt_domain_info_memory_usage_bytes{project_name=\"$project_name\",instance=~\"$compute_node\"}, userId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_info_cpu_time_seconds_total{instanceName=~\"$vm_name\"\r\n,instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"}[10m])/(libvirt_domain_info_virtual_cpus{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"})*100",
     "legendFormat": "{{instanceName}}"
    },
    {}
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(libvirt_domain_stat_memory_available_bytes{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"}-libvirt_domain_stat_memory_unused_bytes{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"})/libvirt_domain_stat_memory_available_bytes{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"}*100\r\n",
     "legendFormat": "{{instanceName}}"
    },
    {}
   ]
  },
  {
   "title": "硬盘 IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_read_requests_total{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"}[10m])",
     "legendFormat": "{{instanceName}}_{{target_device}}_read"
    },
    {
     "expr": "rate(libvirt_domain_block_stats_write_requests_total{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"}[10m])",
     "legendFormat": "{{instanceName}}_{{target_device}}_write"
    }
   ]
  },
  {
   "title": "硬盘吞吐率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_read_bytes_total{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"}[10m])",
     "legendFormat": "{{instanceName}}_{{target_device}}_read"
    },
    {
     "expr": "rate(libvirt_domain_block_stats_write_bytes_total{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"}[10m])",
     "legendFormat": "{{instanceName}}_{{target_device}}_write"
    }
   ]
  },
  {
   "title": "文件系统使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ceil(libvirt_domain_filesystem_stats_used_percent{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"}*100)",
     "legendFormat": "{{instanceName}}_{{target_device}}"
    },
    {}
   ]
  },
  {
   "title": "网卡吞吐率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_bytes_total{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"} [10m])",
     "legendFormat": "{{instanceName}}_RX"
    },
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_bytes_total{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"} [10m])",
     "legendFormat": "{{instanceName}}_TX"
    }
   ]
  },
  {
   "title": "网卡 PPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(libvirt_domain_interface_stats_receive_packets_total{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"} [10m]))",
     "legendFormat": "{{instanceName}}_RX"
    },
    {
     "expr": "ceil(rate(libvirt_domain_interface_stats_transmit_packets_total{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"} [10m]))",
     "legendFormat": "{{instanceName}}_TX"
    }
   ]
  },
  {
   "title": "网卡 Error/Drop",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_drops_total{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"} [10m])",
     "legendFormat": "{{instanceName}}_RX Drop"
    },
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_drops_total{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"} [10m])",
     "legendFormat": "{{instanceName}}_TX Drop"
    },
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_errors_total{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"} [10m])",
     "legendFormat": "{{instanceName}}_RX Error"
    },
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_errors_total{cloud_id=~\"$cloud_id\",cloud_id=~\".+\",instanceName=~\"$vm_name\",instanceId=~\"$vm_instance_id\",userId=~\"$vm_user_id\"} [10m])",
     "legendFormat": "{{instanceName}}_TX Error"
    }
   ]
  }
 ]
}