{
 "title": "lnjoying Node Exporter",
 "description": "轻量化节点信息采集",
 "tags": [
  "service_light_node",
  "omc",
  "node"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vendor",
    "label": "云厂商",
    "query": {
     "query": "label_values(node_uname_info, vendor)"
    }
   },
   {
    "name": "bp",
    "label": "组织",
    "query": {
     "query": "label_values(node_uname_info,bp_id)"
    }
   },
   {
    "name": "user",
    "label": "用户",
    "query": {
     "query": "label_values(node_uname_info{bp_id=~\"$bp\"},user_id)"
    }
   },
   {
    "name": "site",
    "label": "站点",
    "query": {
     "query": "label_values(node_uname_info{bp_id=~\"$bp\", user_id=~\"$user\"},site_id)"
    }
   },
   {
    "name": "node_id",
    "label": "节点",
    "query": {
     "query": "label_values(node_uname_info{bp_id=~\"$bp\", user_id=~\"$user\", site_id=~\"$site\"},node_id)"
    }
   },
   {
    "name": "nodename",
    "label": "名称",
    "query": {
     "query": "label_values(node_uname_info{bp_id=~\"$bp\", user_id=~\"$user\", site_id=~\"$site\"},nodename)"
    }
   },
   { "name": "interval", "label": "间隔", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "total",
    "label": "主机数",
    "query": {
     "query": "query_result(count(node_uname_info{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\"}))"
    }
   },
   {
    "name": "device",
    "label": "网卡",
    "query": {
     "query": "label_values(node_network_info{node_id=~\"$node_id\", device!~\"'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'\"},device)"
    }
   },
   {
    "name": "maxmount",
    "label": "最大挂载目录",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_name",
    "label": "展示使用的名称",
    "query": {
     "query": "label_values(node_uname_info{node_id=~\"$node_id\", bp_id=\"$bp\", user_id=\"$user\", site_id=\"$site\"},name)"
    }
   },
   { "name": "sname", "label": "查询" }
  ]
 },
 "panels": [
  {
   "title": "最近7天P99资源使用率",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_uname_info{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",nodename=~\"$nodename\",nodename=~\".*$sname.*\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "quantile_over_time(0.99, cpu:usage:rate1m{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",nodename=~\"$nodename\",nodename=~\".*$sname.*\"}[7d:1h])",
     "legendFormat": "CPU使用率P99"
    },
    {
     "expr": "quantile_over_time(0.99, mem:usage:rate1m{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",nodename=~\"$nodename\",nodename=~\".*$sname.*\"}[7d:1h])",
     "legendFormat": "内存使用率P99"
    }
   ]
  },
  {
   "title": "整体总负载与整体平均CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "总负载" }
   ],
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\",mode='system'})",
     "legendFormat": "总核数"
    },
    {
     "expr": "sum(node_load5{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\"})",
     "legendFormat": "总5分钟负载"
    },
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "整体总内存与整体平均内存使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "总内存量" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\"} - node_memory_MemAvailable_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\"})",
     "legendFormat": "总已用"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\"} - node_memory_MemAvailable_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\"}) / sum(node_memory_MemTotal_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\"}))*100",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "整体总磁盘与整体平均磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "总磁盘量" }
   ],
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "总磁盘量"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "总使用量"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",instance=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "资源明细",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{node_id=~\"$node_id\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "总CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{node_id=~\"$node_id\"} / (node_memory_MemTotal_bytes{node_id=~\"$node_id\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(node_filesystem_size_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {node_id=~\"$node_id\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "最大分区({{mountpoint}})使用率"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{node_id=~\"$node_id\"} + 1)/ (node_memory_SwapTotal_bytes{node_id=~\"$node_id\"} + 1))) * 100",
     "legendFormat": "交换分区使用率"
    }
   ]
  },
  {
   "title": "各分区可用空间(EXT.*/XFS)",
   "type": "table",
   "description": "本看板中的：磁盘总量、使用量、可用量、使用率保持和df命令的Size、Used、Avail、Use% 列的值一致，并且Use%的值会四舍五入保留一位小数，会更加准确。\n\n注：df中Use%算法为：(size - free) * 100 / (avail + (size - free))，结果是整除则为该值，非整除则为该值+1，结果的单位是%。\n参考df命令源码：",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(time() - node_boot_time_seconds{node_id=~\"$node_id\"})",
     "legendFormat": "运行时间",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(node_cpu_seconds_total{node_id=~\"$node_id\", mode='system'})",
     "legendFormat": "CPU 核数",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(node_memory_MemTotal_bytes{node_id=~\"$node_id\"})",
     "legendFormat": "总内存",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(rate(node_cpu_seconds_total{node_id=~\"$node_id\",mode=\"iowait\"}[$interval])) * 100",
     "legendFormat": "CPU iowait",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "node_filefd_maximum{node_id=~\"$node_id\"}",
     "legendFormat": "总文件描述符",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "process_max_fds{node_id=~\"$node_id\"}",
     "legendFormat": "最大进程打开文件",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "文件描述符/每秒上下文切换",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{node_id=~\"$node_id\"}",
     "legendFormat": "总使用的文件描述符"
    },
    {
     "expr": "rate(node_context_switches_total{node_id=~\"$node_id\"}[$interval])",
     "legendFormat": "每秒上下文切换次数"
    },
    {
     "expr": "(node_filefd_allocated{node_id=~\"$node_id\"}/node_filefd_maximum{node_id=~\"$node_id\"}) *100",
     "legendFormat": "总使用的文件描述符占比"
    },
    {
     "expr": "(process_open_fds{node_id=~\"$node_id\"}/process_max_fds{node_id=~\"$node_id\"}) *100",
     "legendFormat": "进程使用的文件描述符占比"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{node_id=~\"$node_id\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "系统使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{node_id=~\"$node_id\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "用户使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{node_id=~\"$node_id\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "磁盘IO使用率"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{node_id=~\"$node_id\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "总使用率"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node_id=~\"$node_id\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node_id=~\"$node_id\"} - node_memory_MemAvailable_bytes{node_id=~\"$node_id\"}",
     "legendFormat": "已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{node_id=~\"$node_id\"}",
     "legendFormat": "可用"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{node_id=~\"$node_id\"} / (node_memory_MemTotal_bytes{node_id=~\"$node_id\"})))* 100",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "每秒网络带宽使用$device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{node_id=~\"$node_id\",device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{node_id=~\"$node_id\",device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{node_id=~\"$node_id\"}",
     "legendFormat": "1分钟负载"
    },
    {
     "expr": "node_load5{node_id=~\"$node_id\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "node_load15{node_id=~\"$node_id\"}",
     "legendFormat": "15分钟负载"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{node_id=~\"$node_id\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU总核数"
    }
   ]
  },
  {
   "title": "进程运行状态",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{node_id=~\"$node_id\"}",
     "legendFormat": "运行态的进程",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{node_id=~\"$node_id\"}",
     "legendFormat": "等待IO完成阻塞的进程",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_blocked%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "容量%：{{mountpoint}}"
    },
    {
     "expr": "1 - node_filesystem_files_free{node_id=~\"$node_id\",fstype=~\"ext.?|xfs\"} / node_filesystem_files{node_id=~\"$node_id\",fstype=~\"ext.?|xfs\"}",
     "legendFormat": "Inodes%：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "每秒磁盘读写容量",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{node_id=~\"$node_id\"}[$interval])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{node_id=~\"$node_id\"}[$interval])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{node_id=~\"$node_id\"}[$interval])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{node_id=~\"$node_id\"}[$interval])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "每次IO读写的耗时（参考：小于100ms）",
   "type": "graph",
   "description": "Read time seconds 每个磁盘分区读操作花费的秒数\n\nWrite time seconds 每个磁盘分区写操作花费的秒数\n\nIO time seconds 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted seconds每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{node_id=~\"$node_id\"}[$interval]) / rate(node_disk_reads_completed_total{node_id=~\"$node_id\"}[$interval])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{node_id=~\"$node_id\"}[$interval]) / rate(node_disk_writes_completed_total{node_id=~\"$node_id\"}[$interval])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "每1秒内I/O操作耗时占比（I/O Util）",
   "type": "graph",
   "description": "每一秒钟的自然时间内，花费在I/O上的耗时。（wall-clock time）\n\nnode_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nrate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{node_id=~\"$node_id\"}[$interval])",
     "legendFormat": "{{device}}_每秒I/O操作%"
    }
   ]
  },
  {
   "title": "网络Socket连接信息",
   "type": "graph",
   "description": "Sockets_used - 已使用的所有协议套接字总量\n\nCurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数\n\nUDP_inuse - 正在使用的 UDP 套接字数量\n\nRetransSegs - TCP 重传报文数\n\nOutSegs - TCP 发送的报文数\n\nInSegs - TCP 接收的报文数",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{node_id=~\"$node_id\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{node_id=~\"$node_id\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{node_id=~\"$node_id\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{node_id=~\"$node_id\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{node_id=~\"$node_id\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{node_id=~\"$node_id\"}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{node_id=~\"$node_id\"}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{node_id=~\"$node_id\"}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "每分钟流量$device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "bytes", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{node_id=~\"$node_id\",device=~\"$device\"}[1m])",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{node_id=~\"$node_id\",device=~\"$device\"}[1m])",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  }
 ]
}