{
 "title": "lnjoying Node detail",
 "description": "轻量化节点信息采集",
 "tags": [
  "service_light_node",
  "omc",
  "node_detail"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vendor",
    "label": "云厂商",
    "query": {
     "query": "label_values(node_uname_info, vendor)"
    }
   },
   {
    "name": "bp",
    "label": "组织",
    "query": {
     "query": "label_values(node_uname_info,bp_id)"
    }
   },
   {
    "name": "user",
    "label": "用户",
    "query": {
     "query": "label_values(node_uname_info{bp_id=~\"$bp\"},user_id)"
    }
   },
   {
    "name": "site",
    "label": "站点",
    "query": {
     "query": "label_values(node_uname_info{bp_id=~\"$bp\", user_id=~\"$user\"},site_id)"
    }
   },
   {
    "name": "node_id",
    "label": "节点",
    "query": {
     "query": "label_values(node_uname_info{bp_id=~\"$bp\", user_id=~\"$user\", site_id=~\"$site\"},node_id)"
    }
   },
   {
    "name": "nodename",
    "label": "名称",
    "query": {
     "query": "label_values(node_uname_info{bp_id=~\"$bp\", user_id=~\"$user\", site_id=~\"$site\"},nodename)"
    }
   },
   { "name": "interval", "label": "间隔", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "total",
    "label": "主机数",
    "query": {
     "query": "query_result(count(node_uname_info{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\"}))"
    }
   },
   {
    "name": "device",
    "label": "网卡",
    "query": {
     "query": "label_values(node_network_info{node_id=~\"$node_id\", device!~\"'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'|eth.*\"},device)"
    }
   },
   {
    "name": "maxmount",
    "label": "最大挂载目录",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{bp_id=~\"$bp\",user_id=~\"$user\",site_id=~\"$site\",node_id=~\"$node_id\",fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_name",
    "label": "展示使用的名称",
    "query": {
     "query": "label_values(node_uname_info{node_id=~\"$node_id\", bp_id=\"$bp\", user_id=\"$user\", site_id=\"$site\"},name)"
    }
   },
   { "name": "sname", "label": "查询" }
  ]
 },
 "panels": [
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{node_id=~\"$node_id\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "系统使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{node_id=~\"$node_id\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "用户使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{node_id=~\"$node_id\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "磁盘IO使用率"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{node_id=~\"$node_id\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "总使用率"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node_id=~\"$node_id\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node_id=~\"$node_id\"} - node_memory_MemAvailable_bytes{node_id=~\"$node_id\"}",
     "legendFormat": "已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{node_id=~\"$node_id\"}",
     "legendFormat": "可用"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{node_id=~\"$node_id\"} / (node_memory_MemTotal_bytes{node_id=~\"$node_id\"})))* 100",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{node_id=~\"$node_id\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "容量%：{{mountpoint}}"
    },
    {
     "expr": "1 - node_filesystem_files_free{node_id=~\"$node_id\",fstype=~\"ext.?|xfs\"} / node_filesystem_files{node_id=~\"$node_id\",fstype=~\"ext.?|xfs\"}",
     "legendFormat": "Inodes%：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "每秒网络带宽使用$device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{node_id=~\"$node_id\",device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{node_id=~\"$node_id\",device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  }
 ]
}